### ISSUE TITLE
Where can I download semantic_types.txt?

### ISSUE THREAD

**Issue by Veronicium** [wyim/aci-bench#1]
Hi! I am following the setup guide in `SETUP.md` and downloaded the umls 2022AA metathesaurus version as instructed. I cannot find the `semantic_types.txt` file, which is required by `evaluation/semantic.py`. Can you tell me where I can download or create this file?

Thanks!

**Comment by wyim** [comment]
There is a copy in: resources/semantic_types.txt
For expedience, if you do a soft-link in the same directory, you should get the same result.
