### ISSUE TITLE
What do files under baselines/predictions correspond to?

### ISSUE THREAD

**Issue by Veronicium** [wyim/aci-bench#2]
Hi! I notice that `baselines/predictions` contain the outputs produced by each model. Are these files the ones you use to compute the results in Table 6,7,8,9,10 in your paper? If so, how do the file names correspond to the results in these Tables? (e.g., filenames ending with "division_combined.csv", "full.csv", and "{SECTION_NAME}.csv")

Specifically, I evaluate the results of `BioBART-division-combined` using `evaluate_fullnote.py`. The results of objective_results are:
<img width="716" alt="image" src="https://github.com/wyim/aci-bench/assets/29749047/db42a22a-b473-42f4-9ba3-b45099516ef5">
which doesn't seem to match any of the results on Table 9.

**Comment by velvinnn** [comment]
Hi, thanks for looking into the results. Looks like your score is from the BioBART (division) -  there are some minor difference in Rouge-1 though, I suspect it is from some minor modifications when converting the prediction output to CSV file.
![image](https://github.com/wyim/aci-bench/assets/43040304/08fc78c5-fb0e-4236-8a3d-a14a3cba4df4)

**Comment by Veronicium** [comment]
Hi, sorry for the confusion! I took the wrong screenshot. Here are the results I reproduced (the "reproduced" row):

<img width="719" alt="image" src="https://github.com/wyim/aci-bench/assets/29749047/c7c6204a-7e19-4858-aa43-8f37b26b2011">

**Comment by velvinnn** [comment]
Got it. Just to make sure, are you using our evaluation script? Can you point me to your code and configuration?

**Comment by Veronicium** [comment]
Thanks! I'm using your evaluation scripts by running 
`python evaluation/evaluate_fullnote.py data/challenge_data/clinicalnlp_taskB_test1.csv baselines/predictions/BioBART_clinicalnlp_taskB_test1_division_combined.csv data/challenge_data/clinicalnlp_taskB_test1_metadata.csv`

**Comment by Veronicium** [comment]
Sorry to disturb you again. From my understanding, the 'note' column of 'division_combined.csv' files should be the combination of the 'note' column of all "${section_name}.csv" files. Is that correct?

But it seems that `bart-large-xsum-samsum_clinicalnlp_taskB_test1_subjective.csv` and `bart-large-xsum-samsum_clinicalnlp_taskB_test1_division_combined.csv` do not have a large overlap in the 'note' column:

<img width="1458" alt="image" src="https://github.com/wyim/aci-bench/assets/29749047/ae0657b1-2205-4ca6-8f11-936c4dc33866">

Can you double-check which files you use to compute the "(Division)" scores in the Tables? Thanks!

**Comment by velvinnn** [comment]
Thanks for checking! Looks like it comes from prediction version discrepancies. We have updated the prediction files and you can find the prediction for each section in the folder as baselines/predictions/prediction_sections. Now the overall score should be consistent with the table and each section.

**Comment by Veronicium** [comment]
Thanks for updating!! The numbers match now.
